name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libx11-dev libxrandr-dev libxcursor-dev libxi-dev \
        libxinerama-dev libgl1-mesa-dev

    - name: Run Build
      run: |
        chmod +x ./configure.sh
        ./configure.sh

    - name: Archive build output
      run: |
        mkdir -p output
        cp build/logreader output/  

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: logreader
        path: output/

    - name: Make GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: output/*